# Generated by Django 5.1.1 on 2025-06-08 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=288)),
                ('address', models.CharField(max_length=288)),
                ('citystatezip', models.CharField(max_length=288)),
                ('birthdate', models.DateField()),
                ('phone', models.IntegerField()),
                ('timezone', models.CharField(max_length=288)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=288)),
                ('wholesale_cost', models.DecimalField(decimal_places=3, max_digits=10)),
                ('dims_cm', models.CharField(max_length=288)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.IntegerField(primary_key=True, serialize=False)),
                ('ordered', models.DateField()),
                ('shipped', models.DateField()),
                ('items', models.TextField(blank=True)),
                ('total', models.DecimalField(decimal_places=3, max_digits=20)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querymaze.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querymaze.order')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querymaze.product')),
            ],
        ),
    ]
