# Generated by Django 5.1.1 on 2025-06-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querymaze', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customerid',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='sku',
            new_name='product',
        ),
    ]
