# Generated by Django 5.1.1 on 2025-06-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querymaze', '0002_rename_customerid_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=288),
        ),
    ]
