# Generated by Django 5.1.1 on 2025-06-09 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querymaze', '0003_alter_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='orderid',
            new_name='order',
        ),
    ]
