# Generated by Django 5.1.1 on 2025-06-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querymaze', '0004_rename_orderid_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped',
            field=models.DateTimeField(),
        ),
    ]
